<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangSeeder extends Seeder
{
    public function run()
    {
        $barang = [
            ['nama_barang' => 'Beras Varietas Kristal (Premium)/Kg', 'id_index_kategori' => 1],
            ['nama_barang' => 'Beras Varietas Santana (Premium)/Kg', 'id_index_kategori' => 1],
            ['nama_barang' => 'Beras Varietas 74 (Premium)/Kg', 'id_index_kategori' => 1],
            ['nama_barang' => 'Beras Bulog (Medium)/Kg', 'id_index_kategori' => 1],
            ['nama_barang' => 'Beras Varietas Banda (Medium)/Kg', 'id_index_kategori' => 1],
            ['nama_barang' => 'Gula Pasir Kristal Putih/Kg', 'id_index_kategori' => 11],
            ['nama_barang' => 'Minyak Goreng Tanpa Merek Curah (Sputnik)/Ltr', 'id_index_kategori' => 12],
            ['nama_barang' => 'Minyak Goreng Kemasan Sederhana Bantal /Ltr (fortune)', 'id_index_kategori' => 12],
            ['nama_barang' => 'Minyak Goreng Kemasan Premium (Bimoli)/ Ltr', 'id_index_kategori' => 12],
            ['nama_barang' => 'Minyak Goreng ( Minyak Kita Bantal ) / Ltr', 'id_index_kategori' => 12],
            ['nama_barang' => 'Tepung Terigu Kompas/Kg', 'id_index_kategori' => 13],
            ['nama_barang' => 'Daging Ayam Broiler/Kg', 'id_index_kategori' => 3],
            ['nama_barang' => 'Daging Ayam Kampung/Kg', 'id_index_kategori' => 3],
            ['nama_barang' => 'Daging Sapi Paha Depan/Kg', 'id_index_kategori' => 6],
            ['nama_barang' => 'Daging Sapi Paha Belakang/Kg', 'id_index_kategori' => 6],
            ['nama_barang' => 'Daging Sapi Has Luar (Sirloin)/Kg', 'id_index_kategori' => 6],
            ['nama_barang' => 'Daging Sapi Has Dalam (Ternderloin)/Kg', 'id_index_kategori' => 6],
            ['nama_barang' => 'Daging Sapi Sandung Lamur (Brisket)/Kg', 'id_index_kategori' => 6],
            ['nama_barang' => 'Daging Sapi Tetelan/Kg', 'id_index_kategori' => 6],
            ['nama_barang' => 'Daging Sapi Impor Beku/Kg', 'id_index_kategori' => 6],
            ['nama_barang' => 'Telur Ayam Ras/Kg', 'id_index_kategori' => 5],
            ['nama_barang' => 'Telur Ayam Kampung/Kg', 'id_index_kategori' => 5],
            ['nama_barang' => 'Susu Bubuk Balita Dancow Vanila/350gr', 'id_index_kategori' => 14],
            ['nama_barang' => 'Susu Bubuk Balita SGM Vanila/400gr', 'id_index_kategori' => 14],
            ['nama_barang' => 'Susu Kental Manis Frisian Flag/gr', 'id_index_kategori' => 14],
            ['nama_barang' => 'Tahu/Kg', 'id_index_kategori' => 8],
            ['nama_barang' => 'Tempe/Kg', 'id_index_kategori' => 9],
            ['nama_barang' => 'Bawang Merah (Enrekang)/Kg', 'id_index_kategori' => 4],
            ['nama_barang' => 'Bawang Putih (Honan)/Kg', 'id_index_kategori' => 4],
            ['nama_barang' => 'Bawang Bombay/kg', 'id_index_kategori' => 6],
            ['nama_barang' => 'Ikan Tuna/Kg', 'id_index_kategori' => 7],
            ['nama_barang' => 'Ikan Bandeng/Kg', 'id_index_kategori' => 7],
            ['nama_barang' => 'Ikan Teri Asin/Kg', 'id_index_kategori' => 7],
            ['nama_barang' => 'Ikan Asin/Kg', 'id_index_kategori' => 7],
            ['nama_barang' => 'Ikan Cakalang/Kg', 'id_index_kategori' => 7],
            ['nama_barang' => 'Ikan Kembung/Kg', 'id_index_kategori' => 7],
            ['nama_barang' => 'Garam Bata/Kg', 'id_index_kategori' => 15],
            ['nama_barang' => 'Garam Halus/Kg', 'id_index_kategori' => 15],
            ['nama_barang' => 'Kedelai Lokal/Kg', 'id_index_kategori' => 16],
            ['nama_barang' => 'Kedelai Impor/Kg', 'id_index_kategori' => 16],
            ['nama_barang' => 'Mie Instan/Pcs', 'id_index_kategori' => 17],
            ['nama_barang' => 'Cabe Merah Keriting/Kg', 'id_index_kategori' => 2],
            ['nama_barang' => 'Cabe Merah Besar/Kg', 'id_index_kategori' => 2],
            ['nama_barang' => 'Cabe Rawit Merah/Kg', 'id_index_kategori' => 2],
            ['nama_barang' => 'Cabe Rawit Hijau/Kg', 'id_index_kategori' => 2],
            ['nama_barang' => 'Kacang Tanah/Kg', 'id_index_kategori' => 18],
            ['nama_barang' => 'Kacang Hijau/Kg', 'id_index_kategori' => 18],
            ['nama_barang' => 'Ubi Ketela Pohon/Kg', 'id_index_kategori' => 19],
            ['nama_barang' => 'Jagung Pipilan Kuning/Kg', 'id_index_kategori' => 20],
            ['nama_barang' => 'Harga Pupuk Bersubsidi Urea/Kg', 'id_index_kategori' => 21],
            ['nama_barang' => 'Harga Pupuk Bersubsidi NPK Phonska/Kg', 'id_index_kategori' => 21],
            ['nama_barang' => 'Harga Pupuk Bersubsidi Organik Petroganik/Kg', 'id_index_kategori' => 21],
            ['nama_barang' => 'Harga Pupuk Bersubsidi SP-36/Kg', 'id_index_kategori' => 21],
            ['nama_barang' => 'Harga Pupuk Bersubsidi ZA/Kg', 'id_index_kategori' => 21],
            ['nama_barang' => 'Harga LPG Bersubsidi/3Kg', 'id_index_kategori' => 22],
            ['nama_barang' => 'Semen Tonasa/40Kg', 'id_index_kategori' => 23],
            ['nama_barang' => 'Semen Bosowa/40Kg', 'id_index_kategori' => 23],
            ['nama_barang' => 'Besi Beton 6mm/Btg', 'id_index_kategori' => 24],
            ['nama_barang' => 'Besi Beton 8mm/Btg', 'id_index_kategori' => 24],
            ['nama_barang' => 'Besi Beton 10mm/Btg', 'id_index_kategori' => 24],
            ['nama_barang' => 'Besi Beton 12mm/Btg', 'id_index_kategori' => 24],
            ['nama_barang' => 'Baja Ringan/Btg', 'id_index_kategori' => 25],
            ['nama_barang' => 'Triplek 6mm/Lmbr', 'id_index_kategori' => 26],
            ['nama_barang' => 'Kayu Balok/Btg', 'id_index_kategori' => 27],
            ['nama_barang' => 'Kayu Papan/Lmbr', 'id_index_kategori' => 27],
            ['nama_barang' => 'Paku 3cm/Kg', 'id_index_kategori' => 28],
            ['nama_barang' => 'Paku 4cm/Kg', 'id_index_kategori' => 28],
            ['nama_barang' => 'Paku 5cm/Kg', 'id_index_kategori' => 28],
            ['nama_barang' => 'Paku 7cm/Kg', 'id_index_kategori' => 28],
            ['nama_barang' => 'Paku 10cm/Kg', 'id_index_kategori' => 28],
            ['nama_barang' => 'Benih Padi/Kg', 'id_index_kategori' => 29],
            ['nama_barang' => 'Benih Jagung/Kg', 'id_index_kategori' => 29],
            ['nama_barang' => 'Benih Kedelai/Kg', 'id_index_kategori' => 29],
            ['nama_barang' => 'Udang Basah Sedang/kg', 'id_index_kategori' => 30],
            ['nama_barang' => 'Jeruk Lokal/kg', 'id_index_kategori' => 31],
            ['nama_barang' => 'Pisang Ambon/Sisir', 'id_index_kategori' => 31],
            ['nama_barang' => 'Sawi Hijau', 'id_index_kategori' => 32],
            ['nama_barang' => 'Tomat', 'id_index_kategori' => 10],
            ['nama_barang' => 'Ketimun', 'id_index_kategori' => 32],
            ['nama_barang' => 'Kentang', 'id_index_kategori' => 33],
            ['nama_barang' => 'Kangkung', 'id_index_kategori' => 34],
            ['nama_barang' => 'Kacang Panjang', 'id_index_kategori' => 35],
        ];

        DB::table('barang')->insert($barang);
    }
}
